# .github/workflows/protect-branch.yml
name: 📜 Sync Branch Protection

on:
  push:
    paths:
      - .github/workflows/**.yml
  workflow_dispatch:

permissions:
  contents: write   # needed for branch protection
  checks: read
  pull-requests: write

jobs:
  sync-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Determine status-check contexts
        id: contexts
        run: |
          # Extract workflow names (without extension) as contexts
          contexts=$(for wf in .github/workflows/*.yml; do
            basename "$wf" .yml
          done | paste -sd, -)
          echo "::set-output name=contexts::$contexts"

      - name: Update branch protection via Octokit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = 'main';
            const contexts = core.getInput('contexts').split(',');
            await github.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                required_approving_review_count: 2
              },
              restrictions: null
            });
        inputs:
          contexts: ${{ steps.contexts.outputs.contexts }}
